### ISSUE TITLE
QR code Reader Convert Value

### ISSUE THREAD

**Issue by NengStyleCnb** [Dynamsoft/capture-vision-xamarin-forms-samples#36]
Hello sir,
We have testing on qr reader have some problem that we got below, we are your client at Canadia Bank please help to resolve this problem. Thanks you.

reader text: xxxxxxxxxxxxxxxxxxxxxxxx53038405802KH5920KOI ThÈ VC Lifestylexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
original text: xxxxxxxxxxxxxxxxxxxxxxxx53038405802KH5920KOI Thé VC Lifestylexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

the wrong value is : ### ThÈ  ###

QR code:

![IMAGE 2022-08-05 10:42:41](https://user-images.githubusercontent.com/71743408/182997064-7bb74a9c-244e-48a9-ae76-5d1ae05c0a62.jpg)

**Comment by Dynamsoft-Jerson** [comment]
Hi,

**For Xamarin.Android:**

// suppose `result` is an instance of `TextResult`
byte[] barcodeBytes = new byte[result.BarcodeBytes.Count];
result.BarcodeBytes.CopyTo(barcodeBytes, 0);

Encoding iso88591 = Encoding.GetEncoding("ISO-8859-1");
string newBarcodeText = iso88591.GetString(barcodeBytes);

**For Xamarin.iOS:**

// suppose `result` is an instance of `iTextResult`
string newBarcodeText = result.BarcodeBytes.ToString(Foundation.NSStringEncoding.ISOLatin1);

**Comment by Dynamsoft-Jerson** [comment]
@NengStyleCnb Have you tried it? Is it OK now?

**Comment by NengStyleCnb** [comment]
@Dynamsoft-Jerson Yeah, now it ok thanks you.
